# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "mutest-bridge"
version = "0.0.0"
edition = "2021"

[lib]
# crate-type = ["lib", "rlib"]
crate-type = ["rlib"]

[dependencies]
