# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "mutest"
version = "0.0.0"
edition = "2021"

[dependencies]
mutest-driver = { path = "../mutest-driver" }
