//@ build
//@ stderr: empty

//! This test shows that the `#[rustc_main]` function generated by the built-in test harness
//! refers to test items through paths that are inaccessible from the crate root, and
//! are only valid because of the hygiene of the test harness expansion.
//! These paths cannot be made visible, so we leave them as-is.

#[test]
fn test_at_crate_root() {}

mod private {
    #[test]
    fn test_in_private_mod_accessible_at_crate_root() {}
}

mod outer {
    mod inner {
        #[test]
        fn inaccessible_test_in_nested_private_mod() {}

        mod deeper {
            #[test]
            fn inaccessible_test_in_deeply_nested_private_mod() {}
        }
    }
}

pub mod public {
    mod private {
        #[test]
        fn inaccessible_test_in_private_mod_in_public_mod() {}
    }
}
